### ISSUE TITLE
Team section update

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MSC-Website#31]
Update Secs, Heads, Core and Executive Team in website.
Pm any of the Exbo for pictures and other data.

**Comment by mannadamay12** [comment]
I will take this up

**Comment by Prajit-Sengupta** [comment]
Will take this up

**Comment by RiyaTallsss** [comment]
Will take this up

**Comment by RiyaTallsss** [comment]
Will take this up

**Comment by aarushi353** [comment]
Will take this up

**Comment by Kamalpreet-3223** [comment]
I will like to take this up

**Comment by kapoor2902** [comment]
I would like to take up this issue
