### ISSUE TITLE
Event section update

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MSC-Website#32]
In event section add community workshops, ML workshop, Techmeet for year 2020, internal ideathon, Makeathon3077, Quarter Quell etc.

**Comment by Red-0111** [comment]
I would like to work on this  :D

**Comment by anannyasingh610** [comment]
I would like to work on this. :)

**Comment by Mhuskan** [comment]
I would like to work on this

**Comment by Mhuskan** [comment]
I would like to work on this

**Comment by ShreyaChopra13** [comment]
I would like to take up this issue

**Comment by aarushi353** [comment]
I can do this

**Comment by khushipr** [comment]
I would like to work on this.

**Comment by Ishaan-10** [comment]
I would like to work on this
