### ISSUE TITLE
Events Page Bug.

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MSC-Website#33]
When any of the side card is clicked on Events page, the card clicked should get in center. Instead they tend to be in that position.

**Comment by nitanshjain** [comment]
I would like to take this up

**Comment by thetarandhiman** [comment]
I want to take this up.

**Comment by prateekrusta** [comment]
I want to take this up

**Comment by yash22arora** [comment]
I'll like to work on this
