### ISSUE TITLE
Navbar - Identify active items and show it in html

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MSC-Website#60]
Currently only Home seems active from Navbar, but your responsibility is to change the **is_active** id to the appropriate nav item active.

You must do this in specific html files of the pages.

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to this issue?

**Comment by ritikrajdev** [comment]
> new to open source. can I be assigned to this issue?

Sure Rajshree, Go Ahead !
incase you have any doubt you can contact us on discord.

Preferred ways to do so are :-
* passing page name as context
* creating a block of navitem in base then extending and overwriting it in corresponding html files.

**Comment by ritikrajdev** [comment]
> > new to open source. can I be assigned to this issue?
> 
> Sure Rajshree, Go Ahead !
> incase you have any doubt you can contact us on discord.
> 
> Preferred ways to do so are :-
> * passing page name as context
> * creating a block of navitem in base then extending and overwriting it in corresponding html files.
> 

@RajshreeVats

**Comment by ritikrajdev** [comment]
@RajshreeVats any Updates ?
Is there any estimated time when you will finish the assigned task ?

**Comment by RajshreeVats** [comment]
I will finish it this weekend, had classes to attend!!
