### ISSUE TITLE
Replace Facebook With Linkedin

### ISSUE THREAD

**Issue by ritikrajdev** [MicrosoftStudentChapter/MSC-Website#67]
Replace Facebook With Linkedin in footer.

**Comment by Red-0111** [comment]
I would like to work on it

**Comment by Prajit-Sengupta** [comment]
interested.

**Comment by Meharamt** [comment]
I would like to work on it

**Comment by Prajit-Sengupta** [comment]
I am interested

**Comment by AnshulDadhwal** [comment]
I am interested

**Comment by utkarsh-1905** [comment]
I would like to work on this issue as I have experience in working with HTML markup and I have found the code for this particular issue to work on.

**Comment by ritikrajdev** [comment]
Done in https://github.com/MicrosoftStudentChapter/MSC-Website/pull/69
